### ISSUE TITLE
EthAdapter: Healthchecks missing

### ISSUE THREAD

**Issue by tgip-work** [PharmaLedger-IMI/eth-adapter#1]
It seems that EthAdapter does not support Healthchecks.
It is crucial for Container orchestration platform as Kubernetes to know if a container is ready and/or alive.

1. Please implement a route at, e.g. `/health`, `/check`, `/healthz`, `/readiness`, `/liveness` which does not run any business function but implements checking the health of the application itself and return HTTP 200 if everything is ok.

Please take a look at [https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) and [https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html](https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html)

**Comment by asaccool** [comment]
resolved
