### ISSUE TITLE
EthAdapter: Graceful shutdown is missing

### ISSUE THREAD

**Issue by tgip-work** [PharmaLedger-IMI/eth-adapter#2]
It seems that EthAdapter is missing a graceful shutdown and does not react on sending a `SIGTERM` signal. This means that the container platform (e.g. Kubernetes) wait until grace-period has expired and kills the main process instead.

Not implementing a graceful shutdown behaviour may lead to data integrity loss.

Please take a loook at [https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html](https://expressjs.com/en/advanced/healthcheck-graceful-shutdown.html)

**Comment by asaccool** [comment]
resolved
